language: python
sudo: required
dist: bionic
env:
  - DJANGO_VERSION="Django>=2.1,<2.2"
  - DJANGO_VERSION="Django>=2.2,<3.0"
  - DJANGO_VERSION="Django>=3.0,<3.1"
  - DJANGO_VERSION="Django>=3.1,<3.2"
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
matrix:
  exclude:
    - python: "3.8"
      env: DJANGO_VERSION="Django>=2.1,<2.2"
    - python: "3.9"
      env: DJANGO_VERSION="Django>=2.1,<2.2"
install:
    - python -m pip install -e .
before_script:
    - python -m pip install "$DJANGO_VERSION"
script:
    - python setup.py test
