[tox:tox]
envlist = {py310,py311,py312,py313,py314}-{django42,django50,django51,django52,django60},coverage

[testenv]
deps =
    django42: Django>=4.2,<4.3
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    coverage
    daphne
    django-allauth
    django-debug-toolbar
    django-minio-storage
    django-pipeline
    django-prometheus
    django-redis
    gunicorn
    hypothesis
    pytest
    pytest-django
    python-logging-loki
    rcssmin
    scss
    tox
    uvicorn
    whitenoise
setenv =
    DJANGO_SETTINGS_MODULE = test_df_config.data.settings

[testenv:{py310,py311,py312,py313,py314}-{django42,django50,django51,django52,django60}]
commands =
    python3 -m pytest -v -s --doctest-modules --doctest-glob=df_config/*.py --doctest-glob=df_config/**/*.py

[testenv:coverage]
commands =
    python3 -m coverage run --source='df_config,test_df_config' -m pytest
    python3 -m coverage xml -o build/coverage.xml
    python3 -m coverage report -m
